# Docker-compose configuration for production

version: '2'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        container_name: slack_clone_django
        restart: unless-stopped
        volumes:
            - "./slack_clone/app/build:/app/app/build"
            - "./slack_clone/app/webpack-stats.json:/app/app/webpack-stats.json"
            - "/var/lib/docker-nginx/files/slack_clone/media:/files/media"
            - "/var/lib/docker-nginx/files/slack_clone/assets:/files/assets"
            - "/var/log/slack_clone:/var/log/slack_clone"
        # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
        #  work.
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        command: daphne -b 0.0.0.0 -p 80 slack_clone.asgi:channel_layer
        depends_on:
            - redis
            - django_worker
        external_links:
            - postgres-9.5:postgres

    django_worker:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        container_name: slack_clone_django_worker
        restart: unless-stopped
        volumes:
            - "./slack_clone/app/build:/app/app/build"
            - "./slack_clone/app/webpack-stats.json:/app/app/webpack-stats.json"
            - "/var/lib/docker-nginx/files/slack_clone/media:/files/media"
            - "/var/lib/docker-nginx/files/slack_clone/assets:/files/assets"
            - "/var/log/slack_clone:/var/log/slack_clone"
        # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
        #  work.
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        command: python manage.py runworker
        depends_on:
            - redis
        external_links:
            - postgres-9.5:postgres

    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        # Make this service no-op as we don't actually want it running but do want to use docker-compose file to define
        #  volumes etc.
        restart: "no"
        command: "true"
        volumes:
            - "./slack_clone/app:/app/app"
            - "./slack_clone/static:/app/static:ro"

    redis:
        image: redis:3.2-alpine
        restart: unless-stopped
        volumes:
            - "/var/lib/docker-slack_clone/redis:/data"

# NB: Network with this name must already exist on the server and be used by Nginx and Postgres.
networks:
    default:
        external:
            name: private
